# Sniperkit-Bot
# - Status: analyzed

services:
  crane:
    image: michaelsauter/golang:1.8
    rm: true
    interactive: true
    tty: true
    volume: ["$GOPATH:/go"]
    workdir: /go/src/github.com/sniperkit/snk.fork.michaelsauter-crane
    share-ssh-socket: true
    cmd: ["bash"]

commands:
  test: run crane make test
  build: run crane make build
  build-darwin: run crane make build-darwin
  build-darwin-pro: run crane make build-darwin-pro
  gofmt: run crane gofmt -w crane

accelerated-mounts:
  crane:
    uid: 1000
    gid: 1000
