# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/kingpin"

[[constraint]]
  branch = "master"
  name = "github.com/bjaglin/multiplexio"

[[constraint]]
  name = "github.com/blevesearch/bleve"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/cep21/xdgbasedir"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/color"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-shlex"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-uuid"

[[constraint]]
  branch = "master"
  name = "github.com/hoisie/mustache"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/k0kubun/pp"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
