---
services:

  krane:
    image: golang:1-alpine3.8
    rm: true
    interactive: true
    tty: true
    volume: ["$GOPATH:/go"]
    workdir: /go/src/github.com/sniperkit/snk.fork.michaelsauter-crane
    share-ssh-socket: true
    cmd: ["sh"]

commands:
  test: run krane make test
  build: run krane make build
  build-darwin: run krane make build-darwin
  build-darwin-pro: run krane make build-darwin-pro
  gofmt: run krane gofmt -w krane

accelerated-mounts:
  krane:
    uid: 1000
    gid: 1000
